build { core init timer lib/ld test/local_clock }

create_boot_directory

install_config {
config | prio_levels: 2
+ parent-provides
  + service ROM
  + service IRQ
  + service IO_MEM
  + service IO_PORT
  + service PD
  + service RM
  + service CPU
  + service LOG

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100

+ start timer | priority: 0 | ram: 1M
  + provides | + service Timer

+ start test | priority: -1 | ram: 10M
  + binary test-local_clock
  + config | ld_verbose: yes
-
}

build_boot_image [build_artifacts]

append qemu_args "  -nographic"

run_genode_until "child \"test\" exited with exit value.*\n" 80

grep_output {\[init\] child "test" exited with exit value}

compare_output_to {[init] child "test" exited with exit value 0}

