build { core init lib/ld test/nova }

create_boot_directory

set config {
	<config>
		<parent-provides>
			<service name="ROM"/>
			<service name="CPU"/>
			<service name="RM"/>
			<service name="PD"/>
			<service name="LOG"/>
		</parent-provides>
		<default-route>
			<any-service> <parent/> </any-service>
		</default-route>
		<start name="test-nova" caps="12350" ram="128M" ld="no">
			<config/>
		</start>
	</config>
}

install_config $config

build_boot_image [build_artifacts]

append qemu_args "-nographic  -smp 2"

run_genode_until {Test finished} 240

puts "\nTest succeeded"
