create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/init

build { test/framebuffer drivers/framebuffer/boot }

install_config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="100"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="fb_drv" caps="120">
		<binary name="boot_fb_drv"/>
		<resource name="RAM" quantum="64M"/>
		<config/>
	</start>

	<start name="test-framebuffer">
		<resource name="RAM" quantum="10M"/>
		<provides> <service name="Capture"/> </provides>
		<config/>
	</start>

</config>}

build_boot_image [build_artifacts]

run_genode_until forever
